#pragma config(Sensor, S1,     leftSensor,     sensorEV3_Color)
#pragma config(Sensor, S2,     Gyroscope,      sensorEV3_Gyro)
#pragma config(Sensor, S3,     attachmentSensor, sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     rightSensor,    sensorEV3_Color)
#pragma config(Motor,  motorA,          backAttachment, tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorD,          frontAttachment, tmotorEV3_Medium, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "MiscDrivingFunctions.C"
#include "EncoderDrivingFunctions.C"
#include "GyroFunctions.C"
#include "LineFollowingFunctions.C"
#include "GyroDrivingFunctions.C"
#include "TurningFunctions.C"
#include "AttachmentFunctions.C"
#include "Missions.C"

int colorValue;

task main()
{



	//loop forever
	while (true)
	{

		// Check the color sensor for the value
		colorValue = getColorName(attachmentSensor);

		// Check for any button pressed
		if (getButtonPress(buttonAny))
		{

			// Get the value for the color of the attachment
			colorValue = getColorName(attachmentSensor);

			//------------------------
			// Value for get color
			//------------------------
			// Nothing = 0		Clean Wheels
			// Blue = 2				Final Mission
			// Green = 	1			Push Mission
			// Yellow = 7			East Mission
			// Orange =
			// Red = 5				Crane Mission


			if (getButtonPress(buttonLeft))
			{
				cleanWheels();
			}
			else
			{

				// Check for white - Tree Mission
				if (colorValue == 0) treeMission();

				// Check for Yellow(7) - East Mission
				if (colorValue == 7) eastMission();

				// Check for Red(5) - Crane Mission
				if (colorValue == 5) craneMission();

				// Check for Green(1) - Building Push Mission
				if (colorValue == 1) pushMission();

				// Check for Blue(2) - Final Mission
				if (colorValue == 2)	finalMission();

			}
		}

		// If no button pressed, display gyro on line #1
		displayGyro();

		// Display the color reading on Line #2
		displayBigTextLine(3, "Color: %d", colorValue);


	}
}
